### ISSUE TITLE
Unable to find starter template for https://github.com/chrisgriffith/Ionic2Weather

### ISSUE THREAD

**Issue by tama3bb** [chrisgriffith/Ionic2Weather#2]
```
$ ionic start Ionic2Weather https://github.com/chrisgriffith/Ionic2Weather
Unable to find starter template for https://github.com/chrisgriffith/Ionic2Weather
```

How to solve the issue?

```
$ ionic --v
3.3.0
```

**Comment by chrisgriffith** [comment]
With Ionic CLI version 3, the use of third party templates was removed.  Create a new Ionic application using ionic start Ionic2Weather sidemenu. Once you have created the starter Ionic application, download this repo and copy over the src and www directories into the newly created folder, replacing the initial src and www directory. You will still need to follow any additional steps in the book.

**Comment by guy-roberts** [comment]
Bought the book last week, came here for same issue.  Perhaps it needs updating to avoid others asking the same question.  The achilles heel of Ionic is that it changes to often.

**Comment by chrisgriffith** [comment]
Yes, it does. We are almost done with a revised edition that addresses that issue (among other minor tweaks). A guide to the changes can be found at: http://ionic2book.com/downloads/UpgradingToIonic3.pdf

**Comment by guy-roberts** [comment]
Thanks, the upgrade notes are useful.  

From a readers point of view, it would be ideal to have the full example code in a git repo, with branches for each version of Ionic, and tags for each stage of development.  Then people could just checkout the version they need, at the development stage they need.  

Thanks again for the prompt reply.

**Comment by chrisgriffith** [comment]
There are final branches for each of the 3 apps available.

**Comment by guy-roberts** [comment]
Oh great, I missed that.
